- name: Install Anaconda3
  hosts: MLFlow_Group
  become: true
  tasks:
    - name: Get anaconda bash script
      get_url:
        url: https://repo.anaconda.com/archive/Anaconda3-2022.05-Linux-x86_64.sh
        dest: /home/ubuntu/install-anaconda.sh
    
    - name: Create conda folder
      become: True
      file:
        path: /home/ubuntu/anaconda3
        state: directory
        owner: ubuntu
        mode: 755
        recurse: yes
    
    - name: Run the installer
      shell: bash /home/ubuntu/install-anaconda.sh -b -u -p /home/ubuntu/anaconda3
    
    - name: Remove the installer
      file:
        state: absent
        path: /home/ubuntu/install-anaconda.sh
    
    - name: Add anaconda bin to path
      become: True
      shell: echo 'export PATH=/home/ubuntu/anaconda3/bin:$PATH' >> /etc/profile
    
    - name: Conda - read permission for all
      become: True
      file:
        path: /home/ubuntu/anaconda3
        mode: +r
        recurse: yes
    
    - name: conda - execution permission for all
      become: True
      file:
        path: /home/ubuntu/anaconda3/bin
        mode: +x
        recurse: yes