- name: MLFlow Installation
  hosts: MLFlow_Group
  vars_files:
    - /home/ubuntu/vars/variables.yml
  become: true
  tasks:
    - name: Update using apt
      apt:
        update_cache: true

    - name: Update using apt-get
      apt:
        update_cache: true
        force_apt_get: yes

    - name: Check whether conda folder exists or not
      stat:
        path: /home/ubuntu/anaconda3
      register: anaconda_folder

    - name: Setup Anaconda3
      block:
        - name: Install anaconda3
          import_playbook: ./mlflow/conda.yml

      when: anaconda_folder.stat.exists == False
      become: true

    - name: Create mlflow environment
      shell: "/home/ubuntu/anaconda3/bin/conda create -n '{{mlflow.env_name}}' python=3.7.6 -y"
      args:
        executable: /usr/bin/bash

    - name: Activate mlflow environment
      shell: "source /home/ubuntu/anaconda3/bin/activate '{{mlflow.env_name}}'"
      args:
        executable: /usr/bin/bash

    - name: Install pip3,nginx
      apt:
        name: 
          - python3-pip
          - nginx
        state: present

    - name: Install mlflow,passlib via pip3
      ansible.builtin.pip:
        name: 
          - mlflow
          - passlib
        state: present

    - name: Install Apache Utils
      apt:
        name: apache2-utils
        update_cache: yes
        force_apt_get: yes

    - name: Set user name and password for nginx
      community.general.htpasswd:
        path: /etc/nginx/.htpasswd
        name: "{{mlflow.username}}"
        password: "{{mlflow.password}}"

    - name: Copy the nginx configuration file
      ansible.builtin.copy:
        src: /home/ubuntu/mlflow
        dest: /etc/nginx/sites-enabled/

    - name: Restart nginx service
      service:
        name: nginx
        state: restarted

    - name: Copy the mlflow service file
      ansible.builtin.copy:
        src: /home/ubuntu/mlflow-tracking.service
        dest: /etc/systemd/system/

    - name: Reload the daemon
      systemd:
        daemon_reload: yes

    - name: Enable mlflow tracking service
      systemd:
        name: mlflow-tracking
        enabled: yes

    - name: Start mlflow tracking service
      systemd:
        name: mlflow-tracking
        state: started
