- name: Apache Installation
  hosts: Apache_Group
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Ensure Apache has started
      service:
        name: apache2
        state: started
        enabled: yes
