- name: Setup Docker
  hosts: Jenkins_Group
  become: true
  tasks:
    - name: Get convenience script
      shell: curl -fsSL https://get.docker.com -o get-docker.sh

    - name: Run the convenience script
      shell: sudo sh get-docker.sh

    - name: Set permission for ubuntu user
      shell: sudo usermod -aG docker ubuntu