- name: Setup Docker
  hosts: Jenkins_Group
  become: true
  tasks:
    - name: Update using apt
      apt:
        update_cache: true

    - name: Update using apt-get
      apt:
        update_cache: true
        force_apt_get: yes

    - name: Get convenience script
      shell: curl -fsSL https://get.docker.com -o get-docker.sh

    - name: Run the convenience script
      shell: sudo sh get-docker.sh

    - name: Remove the convenience script
      file:
        state: absent
        path: /home/ubuntu/get-docker.sh

    - name: Set permission for ubuntu user
      shell: sudo usermod -aG docker ubuntu
