- name: Setup Jenkins
  hosts: Jenkins_Group
  roles:
    - cloudalchemy.node_exporter
  become: true
  tasks:
    - name: Update apt
      apt:
        update_cache: true

    - name: Update using apt-get
      apt:
        update_cache: true

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Add Jenkins Repositry Key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present

    - name: Configure Jenkins Repositry
      apt_repository:
        repo: "deb https://pkg.jenkins.io/debian-stable binary/"
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started

    - name: Get Jenkins initial password
      shell: sudo cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_initial_password

    - debug:
        msg: "Jenkins initial password : {{jenkins_initial_password.stdout}}"
