- name: Setup Prometheus in EKS cluster
  hosts: Application_Group
  vars_files:
    - /home/ubuntu/vars/variables.yml
  become: true
  tasks:
    - name: Update using apt 
      apt:
        update_cache: true
    
    - name: Update using apt-get 
      apt:
        update_cache: true
        force_apt_get: yes

    - name: Get the helm installer bash script
      shell: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
  
    - name: Change permissions for helm installer bash script
      shell: chmod 700 get_helm.sh

    - name: Run the helm installer bash script
      shell: bash /home/ubuntu/get_helm.sh

    - name: Remove the helm installer bash script
      file: 
        state: absent 
        path: /home/ubuntu/get_helm.sh

    - name: Add helm stable repo
      become: false
      shell: helm repo add stable https://charts.helm.sh/stable
      
    - name: Add prometheus helm repo
      become: false
      shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      
    - name: Update the helm repo
      become: false
      shell: helm repo update

    - name: Install pip3,unzip,jq
      apt:
        name: 
          - python3-pip
          - unzip
          - jq
        state: present
        
    - name: Get and unarchive the awscli zip file
      ansible.builtin.unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /home/ubuntu
        remote_src: yes

    - name: Install awscli from source
      shell: sudo ./aws/install

    - name: Update kubeconfig
      become: false
      shell: aws eks update-kubeconfig --name '{{k8s.cluster_name}}'

    - name: Create a namespace for prometheus
      become: false
      shell: kubectl create namespace monitor
      
    - name: Install the prometheus helm chart
      become: false
      shell: helm install stable prometheus-community/kube-prometheus-stack -n monitor
      
    - name: Patch load balancer to prometheus server
      become: false 
      shell: kubectl patch svc stable-kube-prometheus-sta-prometheus -n monitor -p '{"spec":{"type":"LoadBalancer"}}'

    - name: Patch load balancer to grafana server
      become: false
      shell: kubectl patch svc stable-grafana -n monitor -p '{"spec":{"type":"LoadBalancer"}}'

    - name: Wait till load balancer ip address is available
      shell: sleep 5
    
    - name: Get load balancer url for grafana dashboard
      become: false
      shell: kubectl get svc stable-grafana -n monitor -o json | jq .status.loadBalancer.ingress[0].hostname
      register: grafana_url

    - name: Get load balancer url for prometheus dashboard
      become: false
      shell: kubectl get svc stable-kube-prometheus-sta-prometheus -n monitor -o json | jq .status.loadBalancer.ingress[0].hostname
      register: prometheus_url

    - debug:
        msg: "Open with port 9090,Prometheus url is {{ prometheus_url.stdout }}"
        
    - debug:
        msg: "Grafana url is {{ grafana_url.stdout }}"