- name: Terraform Installation
  hosts: Jenkins_Group
  become: true
  tasks:
    - name: Update using apt-get
      become: true
      apt:
        update_cache: true
        force_apt_get: yes

    - name: Install other packages
      apt:
        name:
          - gnupg
          - software-properties-common
          - curl
        state: present
        force_apt_get: yes

    - name: Get Terraform Repository key
      apt_key: url="https://apt.releases.hashicorp.com/gpg" state=present

    - name: Add Terraform Repository key
      shell: sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

    - name: Update using apt-get
      become: true
      apt:
        update_cache: true
        force_apt_get: yes

    - name: Install Terraform
      become: true
      apt:
        name: terraform
        state: present
        force_apt_get: yes

    - name: Check Terraform version
      shell: "terraform --version"
      register: command_output

    - debug:
        var: command_output.stdout_lines
